#!/usr/bin/env python3

import argparse
import sys

import Screens

parser = argparse.ArgumentParser(description='Runlength encode screen data.')

parser.add_argument("input_file")
parser.add_argument("output_file")
parser.add_argument("-D", action="append", dest="defines")
args = parser.parse_args()

input_file_name = args.input_file
output_file_name = args.output_file


screens = Screens.Screens(defines=args.defines)
if not screens.convert(input_file_name, output_file_name):
    sys.exit(1)
