#!/usr/bin/env python3

import sys

if len(sys.argv) < 2:
    print("usage: ", sys.argv[0], " filename.bin\n")
    sys.exit(1)

filename = sys.argv[1]

with open(filename, mode='rb') as file: # b is important -> binary
    screen = file.read()

screen = screen.replace(b'AGB', b'AHB')

with open(filename, 'wb') as file:
    file.write(screen)
